service: sending-messages-cloudfront
provider:
  name: aws
  region: us-west-2
  stage: dev
  deploymentBucket:
    name: sending-messages-codedeployment-bucket-dev
resources:
  Resources:
    CloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: sending-messages-codedeployment-bucket-dev
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          ViewerCertificate:
            CloudFrontDefaultCertificate: true
          Origins:
            - DomainName: sending-messages-codedeployment-bucket-dev.s3.amazonaws.com
              Id: arn:aws:s3:::sending-messages-codedeployment-bucket-dev
              S3OriginConfig:
                OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
          DefaultCacheBehavior:
            TargetOriginId: arn:aws:s3:::sending-messages-codedeployment-bucket-dev
            ForwardedValues:
              QueryString: false
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - PUT
              - DELETE
              - PATCH
              - POST
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
    OriginBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: sending-messages-codedeployment-bucket-dev
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Action:
                - s3:GetObject
              Effect: Allow
              Resource:
                - !Sub
                  - "arn:aws:s3:::sending-messages-codedeployment-bucket-dev/*"
                  - OriginBucketName: sending-messages-codedeployment-bucket-dev
              Principal:
                "AWS": !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"

  Outputs:
    CloudFrontDistributionDomainName:
      Value: !GetAtt CloudFrontDistribution.DomainName
      Export:
        Name: sending-messages-cloudfront-distribution-domain-name
